version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "6790:6790"
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]